### ISSUE TITLE
utimes.node (no such file)

### ISSUE THREAD

**Issue by loverdeveloper** [baileyherbert/utimes#16]
Apple Silicone M1
The latest version (12.0.1 (21A559))
In Electron

> start:main
> cross-env NODE_ENV=development electron -r ts-node/register/transpile-only ./src/main/main.ts

App threw an error during load
Error: dlopen(/projects/neville/release/app/node_modules/utimes/artifacts/utimes.node, 0x0001): tried: '/projects/neville/release/app/node_modules/utimes/artifacts/utimes.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/utimes.node' (no such file), '/usr/lib/utimes.node' (no such file)

**Comment by baileyherbert** [comment]
Hi @loverdeveloper - is this an application you're developing? If it is, did you copy the `node_modules` folder from another machine by chance? Can you try deleting the `node_modules` directory and installing dependencies again?

The `arm64` prebuilt binary for node v14 on darwin is hosted at https://node-utimes.s3.amazonaws.com/4.1.1/Release/utimes-v4.1.1-node-v83-darwin-arm.tar.gz - perhaps you can extract the `utimes.node` file from there and replace it with the one in your node modules to test if the binary wasn't built for the correct architecture?

**Comment by baileyherbert** [comment]
This is now "fixed" in `4.1.1` and `5.0.0`. It turns out that the darwin `arm` binaries were not valid, and there's no simple way to prebuild them with GitHub Actions yet. For now, it will build from source when installing, so build tools will be required.
