### ISSUE TITLE
Unable install on Windows

### ISSUE THREAD

**Issue by vanowm** [baileyherbert/utimes#29]
Getting this error:
```
> npm install utimes
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux"} (current: {"os":"win32"})
npm ERR! notsup Valid os:  linux
npm ERR! notsup Actual os: win32
```

NodeJS v21.5.0
Windows 10

**Comment by baileyherbert** [comment]
The package referenced in the error message (`inotify@1.4.6`) is unrelated to this package. I performed a fresh installation of this package on Windows 10 and `inotify` was not found in the lock file nor `node_modules`.

Most likely, you have another package in your project that is calling upon `inotify`, but hasn't been installed yet. Running `npm install utimes` will install all other remaining dependencies in the project as well.

**Comment by vanowm** [comment]
My mistake, I was using incorrect parameter: `--save=dev` instead of `--save-dev`
