### ISSUE TITLE
Build Error Caused by node-addon-api 3.0.0

### ISSUE THREAD

**Issue by chris-shaw-2011** [baileyherbert/utimes#4]
https://github.com/nodejs/node-addon-api/pull/766

If you update to version 3.0.2 it appears to be fixed

**Comment by baileyherbert** [comment]
I can't reproduce, but I made an attempt to fix this in b0288391104a447756f2efbc4c1d4a8265c1ea2b. Can you update to `4.0.2` and let me know if it builds?

**Comment by chris-shaw-2011** [comment]
I looked into this a bit more and it appears the issue is probably on my side. I created a new package that uses utimes and imported that package into a personal project. It looks like some other package in my personal project is referencing node-addon-api 3.0.1 which is the version that has the above bug. 

If I have my personal project target 3.0.2 it fixes the issue.

**Comment by baileyherbert** [comment]
Ah okay, thanks for the clarification. I'm glad you got everything working. 😄 
Let me know if you run into any further issues, thanks!
