### ISSUE TITLE
Unable to install on Windows 10

### ISSUE THREAD

**Issue by MikeHibbert** [baileyherbert/utimes#5]
I've been trying to install this but I keep getting errors:

` npm install -save utimes
Debugger attached.

> utimes@4.0.2 install C:\Users\hibbe\Documents\Nodejs\Evermore\node_modules\utimes
> node-gyp rebuild

C:\Users\hibbe\Documents\Nodejs\Evermore\node_modules\utimes>if not defined npm_config_node_gyp (node "C:\Users\hibbe\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\hibbe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Debugger attached.
Debugger attached.
Waiting for the debugger to disconnect...
gyp: Call to 'node -p "require('node-addon-api').include_dir"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\hibbe\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hibbe\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\hibbe\Documents\Nodejs\Evermore\node_modules\utimes
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Waiting for the debugger to disconnect...
npm WARN evermore@0.0.1 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! utimes@4.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the utimes@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hibbe\AppData\Roaming\npm-cache\_logs\2020-11-16T15_48_47_768Z-debug.log`

**Comment by baileyherbert** [comment]
Hmm, your output doesn't include any specific errors but I have a decent idea of what the issue might be.

Just to help narrow this down, could you please open a terminal in your app's root directory (where your package.json lies), run the below command, and report back with the output?

```
node -p "require('node-addon-api').include_dir"
```

**Comment by MikeHibbert** [comment]
Here you go:

```
node -p "require('node-addon-api').include_dir"
Debugger attached.
node_modules\node-addon-api
Waiting for the debugger to disconnect...
PS C:\Users\hibbe\Documents\Nodejs\Evermore>
```

**Comment by baileyherbert** [comment]
I believe the "Debugger attached" line is being sent to stderr when node-gyp tries to retrieve the include_dir, and as a result, assumes there is an error. I'll have to look into how I can fix this in the package.

In the meantime, if you can disable debugging (perhaps by using a standalone terminal outside of your IDE), you should be able to install the package.

**Comment by MikeHibbert** [comment]
@baileyherbert good call! I did it in powershell instead and its working great!
