### ISSUE TITLE
Add prebuilt binaries

### ISSUE THREAD

**Issue by baileyherbert** [baileyherbert/utimes#6]
We should set up the project to build and host prebuilt binaries so it can be installed immediately without build tools. 
https://github.com/mapbox/node-pre-gyp

**Comment by akosbalasko** [comment]
Hi @baileyherbert ! I would really like to have this enhancement, could you please have a rough ETA?

**Comment by baileyherbert** [comment]
Hi @akosbalasko! My goal is to have it done in the next day or two.

**Comment by akosbalasko** [comment]
@baileyherbert perfect, thank you so much! :)

**Comment by baileyherbert** [comment]
Added in 2bc58f231a5c613f4090b0cc1fda6303227d4745. This is my first time implementing something like this, but I tested it with several VMs and it seems to work great!

Good luck with your project, @akosbalasko, and let me know if there are any issues! 👍😀

**Comment by akosbalasko** [comment]
@baileyherbert , it works like a charm, thank you so much! 🥇
